/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.JFrame;


/**
 *
 * @author Usuario
 */
public class AccesoUsuario extends javax.swing.JFrame {
    int xMouse, yMouse;
    /**
     * Creates new form AccesoUsuario
     */
    public AccesoUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        PassUser = new javax.swing.JPasswordField();
        Login = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        Pass = new javax.swing.JLabel();
        IncorrectLogin = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1800, 1015));

        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PassUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PassUser.setForeground(new java.awt.Color(153, 153, 153));
        PassUser.setText("***************");
        PassUser.setToolTipText("");
        PassUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PassUserMousePressed(evt);
            }
        });
        PassUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassUserActionPerformed(evt);
            }
        });
        BG.add(PassUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 490, 280, 30));

        Login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Login.setForeground(new java.awt.Color(201, 126, 57));
        Login.setText("INGRESAR");
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LoginMousePressed(evt);
            }
        });
        BG.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 570, -1, -1));

        User.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setText("Usuario");
        BG.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 420, -1, -1));

        Pass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Pass.setForeground(new java.awt.Color(255, 255, 255));
        Pass.setText("Contraseña");
        BG.add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 490, -1, -1));

        IncorrectLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IncorrectLogin.setText("Usuario y/o contraseña incorrecta");
        BG.add(IncorrectLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 390, 220, -1));

        UserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UserName.setForeground(new java.awt.Color(153, 153, 153));
        UserName.setText("Ingrese su nombre de usuario");
        UserName.setPreferredSize(new java.awt.Dimension(90, 22));
        UserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserNameMousePressed(evt);
            }
        });
        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });
        BG.add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 420, 280, 30));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Banner UL (1).jpg"))); // NOI18N
        FONDO.setText("jLabel1");
        BG.add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1800, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameActionPerformed

    private void PassUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassUserActionPerformed

    private void UserNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserNameMousePressed
        IncorrectLogin.setForeground(Color.black);
        if (UserName.getText().equals("Ingrese su nombre de usuario")){
            UserName.setText("");
            UserName.setForeground(Color.BLACK);
        }
        if (String.valueOf(PassUser.getPassword()).isEmpty()){
            PassUser.setText("***************");
            PassUser.setForeground(Color.GRAY);
        }
        
        
    }//GEN-LAST:event_UserNameMousePressed

    private void PassUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassUserMousePressed
        IncorrectLogin.setForeground(Color.black);
        if (String.valueOf(PassUser.getPassword()).equals("***************")){   
            PassUser.setText("");
            PassUser.setForeground(Color.BLACK);
        }
        if (UserName.getText().isEmpty()){
            UserName.setText("Ingrese su nombre de usuario");
            UserName.setForeground(Color.GRAY);   
        }
    }//GEN-LAST:event_PassUserMousePressed

    private void LoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseEntered
       Login.setForeground(new Color(255,159,72));
       
    }//GEN-LAST:event_LoginMouseEntered

    private void LoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseExited
        Login.setForeground(new Color(201, 126, 57));
    }//GEN-LAST:event_LoginMouseExited

    private void LoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMousePressed
        Admin a1 = new Admin();
        if(UserName.getText().equals("ADMIN") && String.valueOf(PassUser.getPassword()).equals("administrador123")){
            a1.setVisible(true);
            this.setVisible(false);
        }else{
            try {
                Thread.sleep(1100);
            } catch (InterruptedException ex) {
                Thread.currentThread().interrupt();
            }
            IncorrectLogin.setForeground(Color.red);
            PassUser.setText("***************");
            PassUser.setForeground(Color.GRAY);
            UserName.setText("Ingrese su nombre de usuario");
            UserName.setForeground(Color.GRAY);   
        }
        
    }//GEN-LAST:event_LoginMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccesoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JLabel FONDO;
    private javax.swing.JLabel IncorrectLogin;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Pass;
    private javax.swing.JPasswordField PassUser;
    private javax.swing.JLabel User;
    private javax.swing.JTextField UserName;
    // End of variables declaration//GEN-END:variables

}
